x-configs: &common_config
  restart: always
  env_file:
    - .env


services:
  db:
    <<: *common_config
    container_name: db
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    <<: *common_config
    container_name: web
    depends_on:
      - db
    build: .
    volumes:
      - ./src:/test/src

  prometheus:
    <<: *common_config
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    <<: *common_config
    image: grafana/grafana:9.5.20
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  nginx:
    <<: *common_config
    container_name: nginx
    image: nginx:1.27.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
  grafana-storage: