x-configs: &common_config
  restart: always
  env_file:
    - .env


services:
  db:
    <<: *common_config
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  web:
    <<: *common_config
    image: 192.168.197.135:5000/django_web:latest
    depends_on:
      - db
    volumes:
      - ./src:/test/src
    ports:
      - "8000:8000"
    command: sh -c "poetry run python3 ./src/manage.py migrate && poetry run python3 ./src/manage.py runserver 0.0.0.0:8000"
    deploy:
      replicas: 2
      restart_policy:
        condition: any

  prometheus:
    <<: *common_config
    image: prom/prometheus:v2.53.1
    volumes:
      - .:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  grafana:
    <<: *common_config
    image: grafana/grafana:9.5.20
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  postgres_data:
  grafana-storage: