x-configs: &common_config
  restart: always
  env_file:
    - .env
  networks:
    - my_network


services:
  db:
    <<: *common_config
    container_name: db
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    <<: *common_config
    container_name: web
    depends_on:
      - db
    build: .
    volumes:
      - ./src:/test/src

  prometheus:
    <<: *common_config
    container_name: prometheus
    image: prom/prometheus:v2.53.1
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    <<: *common_config
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  nginx:
    <<: *common_config
    container_name: nginx
    image: nginx:1.27.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  loki:
    <<: *common_config
    container_name: loki
    image: grafana/loki:2.9.2
    volumes:
      - ./loki/config/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki/data:/data/loki
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    <<: *common_config
    container_name: promtail
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/config/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml

volumes:
  postgres_data:
  grafana-storage:

networks:
  my_network:
    external: true